name: Update Packages

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-npm-packages:
    if: startsWith(github.repository, 'vlad-iakovlev/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Update packages
        run: npm up -S
      - name: Run prettier
        run: npm run prettier
      - name: Commit and create PR
        id: create_pr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{secrets.GH_TOKEN}}
          branch: update/update-npm-packages
          commit-message: 'chore: npm update'
          title: 'chore: npm update'
          body: Update NPM Packages
          assignees: vlad-iakovlev
      - name: Enable Pull Request Automerge
        if: steps.create_pr.outputs.pull-request-number
        run: gh pr merge --squash --auto ${{ steps.create_pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
